# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

In [1]:
# To use numpy 
import numpy as np

## NumPy Arrays

Numpy arrays essentially come in two flavors: `Vectors` and `Matrices`.
Vectors are strictly 1-d arrays and matrices are 2-d.

In [2]:
# Creating Numpy Arrays
# From a python list
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8 , 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.arange(0, 50, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

## Zeros and Ones

In [9]:
# Generate an array of zeros
np.zeros(3)

array([0., 0., 0.])

In [11]:
# Generate 5 X 5 matrix with zeros
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## linspace
Return evenly spaced number over a specified interval.Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

In [15]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [18]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [19]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [20]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates identity matrix

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random
Numpy also has lots of ways to create random number arrays:

### Rand

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [22]:
np.random.rand(2)

array([0.04281515, 0.46215327])

In [23]:
# Generate 5 X 5 random numbers array
np.random.rand(5, 5)

array([[0.9024611 , 0.60170875, 0.79847347, 0.45116416, 0.42236792],
       [0.36587677, 0.04982928, 0.21791464, 0.51094457, 0.06078485],
       [0.61255055, 0.95515541, 0.4578698 , 0.63166734, 0.63511681],
       [0.88292305, 0.74926603, 0.50067934, 0.31069845, 0.9518852 ],
       [0.87811004, 0.14598105, 0.65198799, 0.41307259, 0.46177266]])

## Randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [25]:
np.random.randn(2)

array([-0.5780691 , -1.79126019])

In [27]:
np.random.randn(5, 5)

array([[ 1.08849395,  0.15398871,  0.12394193,  1.10056166, -0.70421968],
       [-1.96140425,  0.09448726,  1.42731915,  0.33621223, -0.41585976],
       [ 0.24791936,  0.01597326,  0.81792635, -0.41037641, -0.52320152],
       [-1.0362622 , -0.16392438, -1.32689396, -1.94328361, -0.27070069],
       [-0.85610647,  0.4285836 , -0.8404521 ,  1.08147932, -0.38672236]])

## Randint
returns random integers from `low` (inclusive) to `high` (exclusive).

In [31]:
np.random.randint(1,100)

84

In [33]:
np.random.randint(1, 100, 10)

array([10, 19, 26, 20, 44, 71, 92, 91, 41, 18])

## Array attributes and methods

In [34]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr

array([ 2, 46, 31, 23, 34, 19, 17, 30, 29, 45])

## Reshape
Returns an array containing the same data with a new shape.

In [38]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [39]:
ranarr

array([ 2, 46, 31, 23, 34, 19, 17, 30, 29, 45])

In [40]:
#Return the maximum along a given axis.
ranarr.max()

46

In [41]:
#Return the minimum along a given axis.
ranarr.min()

2

In [43]:
#Return indices of the maximum values along the given axis.
ranarr.argmax()

1

In [44]:
#Return indices of the minimum values along the given axis.
ranarr.argmin()

0

## shape
Return the shape of an array. (not a method)

In [45]:
# Vector
arr.shape

(25,)

In [46]:
# notice the two set of brackets
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [47]:
arr.reshape(1,25).shape

(1, 25)

In [48]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [49]:
arr.reshape(25, 1).shape

(25, 1)

In [50]:
arr.dtype

dtype('int64')