In [1]:
# import numpy
import numpy as np

In [13]:
# Create sample array
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection

In [5]:
# The simplest way to pick one or some elements of an array looks very similar to python lists.
arr[8]

8

In [6]:
# Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[:4]

array([0, 1, 2, 3])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting
Broadcasting describes the way numpy treats arrays with different shapes for arithmetic operations. 

In [9]:
#Setting a value with index range(Broadcasting)
arr[0:5] = 100

# Display the arr
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [12]:
# Reset array
arr = np.arange(0, 11)

# show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# Slice
slice_of_arr = arr[0:6]

# Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
# Change the slice
slice_of_arr[:] = 99
# Show slice

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
# now note the changes also occur in our original array!
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
# Data is not copied , it's a view of the original array! this avoids memory problems!
# To get a copy, we need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)
The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. 

In [18]:
arr_2d = np.array(([5, 10, 15], [20, 25, 30], [35, 40, 45]))

# show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
# indexing a row
arr_2d[1]

array([20, 25, 30])

In [21]:
arr_2d[0]

array([ 5, 10, 15])

In [22]:
# Getting individual elements
arr_2d[1][0]

20

In [23]:
arr_2d[1, 0]

20

In [24]:
# 2D array slicing 
# Shape (2, 2) from top right corner
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [25]:
# bottom row
arr_2d[2]

array([35, 40, 45])

In [27]:
arr_2d[2,:]

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [31]:
# Create a matrix
arr2d = np.zeros((10, 10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
#len of array
len(arr2d)

10